### ISSUE TITLE
.env.example is empty (and has a syntax error)

### ISSUE THREAD

**Issue by coolaj86** [nme077/social_fam#8]
What does `CLIENT_ID` refer to? Or `CLOUD_NAME`? And where would I get them?

Could you put in some example values and comments so that it's more clear?

What's optional and what's required?

Can I run this on my own computer on localhost, or does it have to be deployed on a particular cloud platform?

Also, `REDIRECT-URI=` is incorrect.

**Comment by nme077** [comment]
@coolaj86 Thanks for bringing this issue to my attention. I have updated the .env.example to clear up the issues you mentioned. I also added more detailed instructions on the [README](https://github.com/nme077/social_fam#readme) Take a look and let me know if you think it could be clearer.
